---
- name: Check if OpenVPN was previously deployed
  ansible.builtin.stat:
    path: "{{ __pivpn__ovpn_config_dir }}"
  register: pivpn__openvpn_deployed

- name: Deploy OpenVPN
  when: not pivpn__openvpn_deployed.stat.exists
  block:
    - name: Create the PiVPN temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: pivpn__temp_dir

    - name: Deploy the OpenVPN installation files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ pivpn__temp_dir.path }}/{{ item.dest }}"
        mode: "644"
      with_items:
        - { src: ovpn-installation.conf.j2, dest: ovpn-installation.conf }

    - name: Download the PiVPN installation script
      ansible.builtin.get_url:
        url: "{{ __pivpn__installer }}"
        dest: "{{ pivpn__temp_dir.path }}/pivpn.bash"
        mode: "755"

    - name: Run the installation script for OpenVPN
      ansible.builtin.command: "{{ pivpn__temp_dir.path }}/pivpn.bash --unattended {{ pivpn__temp_dir.path }}/{{ item }}"
      with_items:
        - ovpn-installation.conf
      changed_when: false

    - name: Remove the PiVPN temporary directory
      ansible.builtin.file:
        path: "{{ pivpn__temp_dir.path }}"
        state: absent

- name: Enable OpenVPN port-share functionality
  ansible.builtin.lineinfile:
    path: /etc/openvpn/server.conf
    regexp: ^port-share
    line: port-share {{ pivpn__ovpn_port_share_host }} {{ pivpn__ovpn_port_share_port }}
    backup: true
  notify: Restart openvpn@server.service
  when: pivpn__ovpn_enable_port_share
