---
- name: Check if WireGuard was previously deployed
  ansible.builtin.stat:
    path: "{{ __wireguard_configuration_directory }}"
  register: wireguard_deployed

- name: Deploy WireGuard
  when: not wireguard_deployed.stat.exists
  block:
    - name: Create the PiVPN temporary directory
      ansible.builtin.file:
        path: "{{ __pivpn_tmp_dir }}"
        state: directory
        mode: "755"

    - name: Deploy the WireGuard installation files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ __pivpn_tmp_dir }}/{{ item.dest }}"
        mode: "644"
      with_items:
        - { src: wireguard-installation.conf.j2, dest: wireguard-installation.conf }

    - name: Download the PiVPN installation script
      ansible.builtin.get_url:
        url: "{{ __pivpn_installer_url }}"
        dest: "{{ __pivpn_installation_script }}"
        mode: "755"

    - name: Run the installation script for WireGuard
      ansible.builtin.command: "{{ __pivpn_installation_script }} --unattended {{ __pivpn_tmp_dir }}/{{ item }}"
      with_items:
        - wireguard-installation.conf
      changed_when: false

    - name: Remove the PiVPN temporary directory
      ansible.builtin.file:
        path: "{{ __pivpn_tmp_dir }}"
        state: absent
