---
- name: Check if WireGuard was previously deployed
  ansible.builtin.stat:
    path: "{{ __pivpn__wgrd_config_dir }}"
  register: pivpn__wireguard_deployed

- name: Deploy WireGuard
  when: not pivpn__wireguard_deployed.stat.exists
  block:
    - name: Create the PiVPN temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: pivpn__temp_dir

    - name: Deploy the WireGuard installation files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ pivpn__temp_dir }}/{{ item.dest }}"
        mode: "644"
      with_items:
        - { src: wgrd-installation.conf.j2, dest: wgrd-installation.conf }

    - name: Download the PiVPN installation script
      ansible.builtin.get_url:
        url: "{{ __pivpn__installer }}"
        dest: "{{ pivpn__temp_dir }}/pivpn.bash"
        mode: "755"

    - name: Run the installation script for WireGuard
      ansible.builtin.command: "{{ pivpn__temp_dir }}/pivpn.bash --unattended {{ pivpn__temp_dir }}/{{ item }}"
      with_items:
        - wgrd-installation.conf
      changed_when: false

    - name: Remove the PiVPN temporary directory
      ansible.builtin.file:
        path: "{{ pivpn__temp_dir }}"
        state: absent
