---
- name: Deploy WireGuard
  ansible.builtin.import_tasks: deploy-wgrd.yml
  when: pivpn__deploy_wgrd

- name: Deploy OpenVPN
  ansible.builtin.import_tasks: deploy-ovpn.yml
  when: pivpn__deploy_ovpn
